version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps):"
    labels:
      - "auto-deps"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
          - "rxjs"
          - "zone.js"
